In [208]:
conda activate <env>
conda install pip
pip freeze > requirements.txt

SyntaxError: invalid syntax (1112955658.py, line 1)

In [ ]:
#Importing Packages

# Importing Pandas for data manipulation and analysis
import pandas as pd

# Importing NumPy for numerical operations
import numpy as np

# Importing Matplotlib for data visualization
import matplotlib.pyplot as plt

# Importing Seaborn for advanced data visualization
import seaborn as sns

# Importing IPython.display for displaying rich media in Jupyter Notebooks
from IPython.display import display, Image

# Importing IPython.display for displaying rich media in Jupyter Notebooks
import nltk
from nltk.corpus import stopwords

# Importing models used for training
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression

# Importing model metrics to evaluate performance
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
import pickle


Note: you may need to restart the kernel to use updated packages.


<h3 style=\"color:green;\">DATA LOADING</h3>
    
    Firstly, import the necessary packages. When the required packages are imported, for loading a CSV file, this Project will utilise Pandas to load the data.

In [196]:
# Load the CSV file
train_df = pd.read_csv('Data/processed/train.csv')
test_df = pd.read_csv('Data/processed/test.csv')

In [197]:
test_df.head()

headlines  \
0  NLC India wins contract for power supply to Ra...   
1  SBI Clerk prelims exams dates announced; admit...   
2  Golden Globes: Michelle Yeoh, Will Ferrell, An...   
3  OnePlus Nord 3 at Rs 27,999 as part of new pri...   
4  Adani family’s partners used ‘opaque’ funds to...   

                                         description  \
0  State-owned firm NLC India Ltd (NLCIL) on Mond...   
1  SBI Clerk Prelims Exam: The SBI Clerk prelims ...   
2  Barbie is the top nominee this year, followed ...   
3  New deal makes the OnePlus Nord 3 an easy purc...   
4  Citing review of files from multiple tax haven...   

                                             content  \
0  State-owned firm NLC India Ltd (NLCIL) on Mond...   
1  SBI Clerk Prelims Exam: The State Bank of Indi...   
2  Michelle Yeoh, Will Ferrell, Angela Bassett an...   
3  In our review of the OnePlus Nord 3 5G, we pra...   
4  Millions of dollars were invested in some publ...   

                                                 url       category  
0  https://indianexpress.com/article/business/com...       business  
1  https://indianexpress.com/article/education/sb...      education  
2  https://indianexpress.com/article/entertainmen...  entertainment  
3  https://indianexpress.com/article/technology/t...     technology  
4  https://indianexpress.com/article/business/ada...       business

In [198]:
train_df.head()

headlines  \
0  RBI revises definition of politically-exposed ...   
1  NDTV Q2 net profit falls 57.4% to Rs 5.55 cror...   
2  Akasa Air ‘well capitalised’, can grow much fa...   
3  India’s current account deficit declines sharp...   
4  States borrowing cost soars to 7.68%, highest ...   

                                         description  \
0  The central bank has also asked chairpersons a...   
1  NDTV's consolidated revenue from operations wa...   
2  The initial share sale will be open for public...   
3  The current account deficit (CAD) was 3.8 per ...   
4  The prices shot up reflecting the overall high...   

                                             content  \
0  The Reserve Bank of India (RBI) has changed th...   
1  Broadcaster New Delhi Television Ltd on Monday...   
2  Homegrown server maker Netweb Technologies Ind...   
3  India’s current account deficit declined sharp...   
4  States have been forced to pay through their n...   

                                                 url  category  
0  https://indianexpress.com/article/business/ban...  business  
1  https://indianexpress.com/article/business/com...  business  
2  https://indianexpress.com/article/business/mar...  business  
3  https://indianexpress.com/article/business/eco...  business  
4  https://indianexpress.com/article/business/eco...  business

<h3 style=\"color:green;\">PRE-PROCESSING</h3>
    
- Remove unnecessary columns (url) since it may not contribute to categorization.
- *Text Cleaning*: Convert text to lowercase, remove punctuation, stopwords, and special characters.
- *Tokenization*: Split text into individual words or phrases.
- *Vectorization*: Convert text into numerical form using TF-IDF or CountVectorizer.

In [199]:
#Remove unnecessary columns
train_df = train_df.drop('url', axis=1)
train_df.head()

headlines  \
0  RBI revises definition of politically-exposed ...   
1  NDTV Q2 net profit falls 57.4% to Rs 5.55 cror...   
2  Akasa Air ‘well capitalised’, can grow much fa...   
3  India’s current account deficit declines sharp...   
4  States borrowing cost soars to 7.68%, highest ...   

                                         description  \
0  The central bank has also asked chairpersons a...   
1  NDTV's consolidated revenue from operations wa...   
2  The initial share sale will be open for public...   
3  The current account deficit (CAD) was 3.8 per ...   
4  The prices shot up reflecting the overall high...   

                                             content  category  
0  The Reserve Bank of India (RBI) has changed th...  business  
1  Broadcaster New Delhi Television Ltd on Monday...  business  
2  Homegrown server maker Netweb Technologies Ind...  business  
3  India’s current account deficit declined sharp...  business  
4  States have been forced to pay through their n...  business

In [200]:
import re
import string
from nltk.tokenize import word_tokenize, TreebankWordTokenizer
#Text Cleaning

# Download stopwords
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

# Function to remove stop words
def clean_text(text):
    # Remove punctuation and special characters
    text = re.sub(r'[^\w\s]', ' ', text)
    # Remove numbers from the text
    text = re.sub(r'\d+', ' ', text)
    # Remove stopwords
    text = ' '.join([word for word in text.split() if word.lower() not in stop_words])
    return text

train_df['cleaned_headlines'] = train_df['headlines'].apply(clean_text)
train_df['cleaned_description'] = train_df['description'].apply(clean_text)
train_df['cleaned_content'] = train_df['content'].apply(clean_text)

# Make the entire column lowercase
train_df['cleaned_headlines'] = train_df['cleaned_headlines'].str.lower()
train_df['cleaned_description'] = train_df['cleaned_description'].str.lower()
train_df['cleaned_content'] = train_df['cleaned_content'].str.lower()

train_df = train_df.drop('content', axis=1)
train_df = train_df.drop('description', axis=1)
train_df = train_df.drop('headlines', axis=1)


train_df.head()

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


category                                  cleaned_headlines  \
0  business  rbi revises definition politically exposed per...   
1  business  ndtv q net profit falls rs crore impacted lowe...   
2  business  akasa air well capitalised grow much faster ce...   
3  business  india current account deficit declines sharply...   
4  business     states borrowing cost soars highest far fiscal   

                                 cleaned_description  \
0  central bank also asked chairpersons chief exe...   
1  ndtv consolidated revenue operations rs crore ...   
2  initial share sale open public subscription ju...   
3  current account deficit cad per cent gdp usd b...   
4  prices shot reflecting overall higher risk ave...   

                                     cleaned_content  
0  reserve bank india rbi changed definition poli...  
1  broadcaster new delhi television ltd monday re...  
2  homegrown server maker netweb technologies ind...  
3  india current account deficit declined sharply...  
4  states forced pay nose weekly auction debt tue...

In [201]:

# Tokenise the text using the TreebankWordTokenizer
#tokeniser = TreebankWordTokenizer()
#train_df['tokens_content'] = train_df['cleaned_content'].apply(tokeniser.tokenize)
#train_df['tokens_description'] = train_df['cleaned_description'].apply(tokeniser.tokenize)
#train_df['tokens_headlines'] = train_df['cleaned_headlines'].apply(tokeniser.tokenize)

#train_df = train_df.drop('cleaned_content', axis=1)
#train_df = train_df.drop('cleaned_description', axis=1)
#train_df = train_df.drop('cleaned_headlines', axis=1)

#train_df.head()

In [202]:
#from sklearn.feature_extraction.text import CountVectorizer

# Initialise CountVectorizer
#vect = CountVectorizer()
# Fit the CountVectorizer on the preprocessed 'post' column
#vect.fit(train_df['cleaned_content'] )

Setup training data

In [203]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
X_vectorized = vectorizer.fit_transform(train_df["cleaned_headlines"]) 

In [204]:
X_vect = vect
y = train_df["category"]

In [205]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_vectorized, y, test_size=0.2, random_state=42)

Model training and 

In [ ]:


# Save the trained model

# Train Naive Bayes
nb = MultinomialNB()
nb.fit(X_train, y_train)
nb_pred = nb.predict(X_test)
with open("Streamlit/Naive_Bayes.pkl", "wb") as f:
    pickle.dump(nb, f)

# Train SVM
svm = SVC(kernel="linear")
svm.fit(X_train, y_train)
svm_pred = svm.predict(X_test)
with open("Streamlit/SVM.pkl", "wb") as f:
    pickle.dump(svm, f)

# Save Vectorizer
with open("Streamlit/vectorizer.pkl", "wb") as f:
    pickle.dump(vectorizer, f)

# Evaluate Models
print("Naive Bayes Accuracy:", accuracy_score(y_test, nb_pred))
print("SVM Accuracy:", accuracy_score(y_test, svm_pred))

Naive Bayes Accuracy: 0.9039855072463768
SVM Accuracy: 0.9320652173913043


Test trained models

In [192]:

test_df['cleaned_headlines'] = test_df['headlines'].apply(clean_text)
test_df['cleaned_description'] = test_df['description'].apply(clean_text)
test_df['cleaned_content'] = test_df['content'].apply(clean_text)

# Make the entire column lowercase
test_df['cleaned_headlines'] = test_df['cleaned_headlines'].str.lower()
test_df['cleaned_description'] = test_df['cleaned_description'].str.lower()
test_df['cleaned_content'] = test_df['cleaned_content'].str.lower()

test_df = test_df.drop('content', axis=1)
test_df = test_df.drop('description', axis=1)
test_df = test_df.drop('headlines', axis=1)

#vectorizer = TfidfVectorizer()
X_test_vectorized = vectorizer.transform(test_df["cleaned_headlines"]) 
y_test = test_df["category"]



Checking Performance of models on unseen data

In [193]:
from sklearn.metrics import confusion_matrix
X_train2, X_test2, y_train2, y_test2 = train_test_split(X_test_vectorized, y_test, test_size=0.2, random_state=42)


nb_pred2 = nb.predict(X_test2)
svm_pred2= svm.predict(X_test2)

# Evaluate Models
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, log_loss

nb_cm = confusion_matrix(y_test2, nb_pred2)
nb_accuracy = accuracy_score(y_test2, nb_pred2)
nb_precision = precision_score(y_test2, nb_pred2, average='weighted')
nb_recall = recall_score(y_test2, nb_pred2, average='weighted')
nb_f1 = f1_score(y_test2, nb_pred2, average='weighted')
nb_auc_roc = roc_auc_score(y_test2, nb.predict_proba(X_test2), multi_class='ovr')
nb_log_loss_val = log_loss(y_test2, nb.predict_proba(X_test2))

svm_accuracy = accuracy_score(y_test2, svm_pred2)
svm_precision = precision_score(y_test2, svm_pred2, average='weighted')
svm_recall = recall_score(y_test2, svm_pred2, average='weighted')
svm_f1 = f1_score(y_test2, svm_pred2, average='weighted')
svm_cm = confusion_matrix(y_test2, svm_pred2)
#svm_auc_roc = roc_auc_score(y_test2, svm.predict_proba(X_test2), multi_class='ovr')
#svm_log_loss_val = log_loss(y_test2, svm.predict_proba(X_test2))

print("Naive Bayes Accuracy:")
print(f"Accuracy: {nb_accuracy:.4f}")
print(f"Precision: {nb_precision:.4f}")
print(f"Recall: {nb_recall:.4f}")
print(f"F1 Score: {nb_f1:.4f}")
print(f"AUC-ROC: {nb_auc_roc:.4f}")
print(f"Log Loss: {nb_log_loss_val:.4f}")
print(nb_cm)
#print(f"confusion_matrix: {nb_cm:.4f}")
print("------------------------------------------")
print("******************************************")
print("------------------------------------------")
print("SVM Accuracy:")
print(f"Accuracy: {svm_accuracy:.4f}")
print(f"Precision: {svm_precision:.4f}")
print(f"Recall: {svm_recall:.4f}")
print(f"F1 Score: {svm_f1:.4f}")
print(svm_cm)
#print(f"AUC-ROC: {svm_auc_roc:.4f}")
#print(f"Log Loss: {svm_log_loss_val:.4f}")

Naive Bayes Accuracy:
Accuracy: 0.8850
Precision: 0.8950
Recall: 0.8850
F1 Score: 0.8821
AUC-ROC: 0.9935
Log Loss: 0.5652
[[66  4  0  0  3]
 [ 0 78  0  0  2]
 [ 0  2 75  0  4]
 [ 7  5  8 59  7]
 [ 3  1  0  0 76]]
------------------------------------------
******************************************
------------------------------------------
SVM Accuracy:
Accuracy: 0.9300
Precision: 0.9320
Recall: 0.9300
F1 Score: 0.9301
[[68  1  1  0  3]
 [ 0 78  0  0  2]
 [ 1  0 76  1  3]
 [ 3  0  5 75  3]
 [ 3  1  0  1 75]]
